//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.HostStringsService.Console.StringsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringsServiceReference.IStringsService")]
    public interface IStringsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/GetFirstStringOccurencesInSecondString", ReplyAction="http://tempuri.org/IStringsService/GetFirstStringOccurencesInSecondStringResponse" +
            "")]
        int GetFirstStringOccurencesInSecondString(string firstString, string secondString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsService/GetFirstStringOccurencesInSecondString", ReplyAction="http://tempuri.org/IStringsService/GetFirstStringOccurencesInSecondStringResponse" +
            "")]
        System.Threading.Tasks.Task<int> GetFirstStringOccurencesInSecondStringAsync(string firstString, string secondString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringsServiceChannel : _04.HostStringsService.Console.StringsServiceReference.IStringsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringsServiceClient : System.ServiceModel.ClientBase<_04.HostStringsService.Console.StringsServiceReference.IStringsService>, _04.HostStringsService.Console.StringsServiceReference.IStringsService {
        
        public StringsServiceClient() {
        }
        
        public StringsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetFirstStringOccurencesInSecondString(string firstString, string secondString) {
            return base.Channel.GetFirstStringOccurencesInSecondString(firstString, secondString);
        }
        
        public System.Threading.Tasks.Task<int> GetFirstStringOccurencesInSecondStringAsync(string firstString, string secondString) {
            return base.Channel.GetFirstStringOccurencesInSecondStringAsync(firstString, secondString);
        }
    }
}
