-- MySQL Script generated by MySQL Workbench
-- 08/23/14 22:30:32
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `FacultyId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FacultyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `DepartmentsId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyId` INT NOT NULL,
  PRIMARY KEY (`DepartmentsId`, `FacultyId`),
  INDEX `fk_Departments_Faculties_idx` (`FacultyId` ASC),
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `mydb`.`Faculties` (`FacultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `CourseId` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `DepartmentsId` INT NOT NULL,
  PRIMARY KEY (`CourseId`, `DepartmentsId`),
  INDEX `fk_Courses_Departments1_idx` (`DepartmentsId` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`DepartmentsId`)
    REFERENCES `mydb`.`Departments` (`DepartmentsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `StudentsId` INT NOT NULL,
  `Name` INT NULL,
  `FacultyId` INT NULL,
  PRIMARY KEY (`StudentsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses_has_Students` (
  `CourseId` INT NOT NULL,
  `StudentsId` INT NOT NULL,
  PRIMARY KEY (`CourseId`, `StudentsId`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`StudentsId` ASC),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`CourseId` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`CourseId`)
    REFERENCES `mydb`.`Courses` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`StudentsId`)
    REFERENCES `mydb`.`Students` (`StudentsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `TitleId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TitleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `ProfessorsId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `TitleId` INT NOT NULL,
  PRIMARY KEY (`ProfessorsId`, `TitleId`),
  INDEX `fk_Professors_Titles1_idx` (`TitleId` ASC),
  CONSTRAINT `fk_Professors_Titles1`
    FOREIGN KEY (`TitleId`)
    REFERENCES `mydb`.`Titles` (`TitleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors_has_Courses` (
  `ProfessorsId` INT NOT NULL,
  `CourseId` INT NOT NULL,
  PRIMARY KEY (`ProfessorsId`, `CourseId`),
  INDEX `fk_Professors_has_Courses_Courses1_idx` (`CourseId` ASC),
  INDEX `fk_Professors_has_Courses_Professors1_idx` (`ProfessorsId` ASC),
  CONSTRAINT `fk_Professors_has_Courses_Professors1`
    FOREIGN KEY (`ProfessorsId`)
    REFERENCES `mydb`.`Professors` (`ProfessorsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Courses_Courses1`
    FOREIGN KEY (`CourseId`)
    REFERENCES `mydb`.`Courses` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
