'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ContextGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Public Partial Class StefanModel
	Inherits OpenAccessContext
	Implements IStefanModelUnitOfWork
	Private Shared connectionStringName As String = ""
	
	Private Shared backend As BackendConfiguration = GetBackendConfiguration()
			
	Private Shared metadataSource As MetadataSource = New StefanModelMetadataSource()
	
	Public Sub New()
		MyBase.New(connectionStringName, backend, metadataSource)
	End Sub
		
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, backend, metadataSource)
	End Sub
		
	Public Sub New(ByVal backendConfiguration As BackendConfiguration)
		MyBase.New(connectionStringName, backendConfiguration, metadataSource)
	End Sub
			
	Public Sub New(ByVal connection As String, ByVal metadataSource As MetadataSource)
		MyBase.New(connection, backend, metadataSource)
	End Sub
			
	Public Sub New(ByVal connection As String, ByVal backendConfiguration As BackendConfiguration, ByVal metadataSource As MetadataSource)
		MyBase.New(connection, backendConfiguration, metadataSource)
	End Sub
		
	Public Sub Reroute_Add(entity As Object) Implements IUnitOfWork.Add
		Me.Add(entity)
	End Sub
	
	Public Sub Reroute_ClearChanges() Implements IUnitOfWork.ClearChanges
		Me.ClearChanges()
	End Sub
	
	Public Sub Reroute_Delete(entity As Object) Implements IUnitOfWork.Delete
		Me.Delete(entity)
	End Sub
	
	Public Function Reroute_GetAll(Of T)() As IQueryable(Of T) Implements IUnitOfWork.GetAll
		Return Me.GetAll(Of T)()
	End Function
	
	Public Function Reroute_GetObjectByKey(Of T)(key As Telerik.OpenAccess.ObjectKey) As T Implements IUnitOfWork.GetObjectByKey
		Return CType(Me.GetObjectByKey(key), T)
	End Function
	
	Public Sub Reroute_SaveChanges() Implements IUnitOfWork.SaveChanges
		Me.SaveChanges()
	End Sub
	Public Shared Function GetBackendConfiguration() As BackendConfiguration
		Dim backend As BackendConfiguration = New BackendConfiguration()
		backend.Backend = "MySql"
		backend.ProviderName = "MySql.Data.MySqlClient"
		
		CustomizeBackendConfiguration(backend)
	
		Return backend
	End Function
	
	''' <summary>
	''' Allows you to customize the BackendConfiguration of StefanModel.
	''' </summary>
	''' <param name="config">The BackendConfiguration of StefanModel.</param>
	Private Shared Partial Sub CustomizeBackendConfiguration(ByRef config As BackendConfiguration)
	End Sub
	
End Class

Public Interface IStefanModelUnitOfWork
	Inherits IUnitOfWork
End Interface
