'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports Telerik.OpenAccess.Metadata.Relational


		Public Partial Class StefanModelMetadataSource 
		Inherits FluentMetadataSource
	
		Protected Overrides Function PrepareMapping() As IList(Of MappingConfiguration)
			Dim mappingConfigurations As New List(Of MappingConfiguration)()
			Return mappingConfigurations
			
		End Function
		
		Protected Overrides Sub SetContainerSettings(container As MetadataContainer)		
			container.Name = "StefanModel"
			container.DefaultNamespace = "DataAccessModel1"
			container.RootNamespace = "DataAccessModel1"
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property
			container.NameGenerator.RemoveCamelCase = false
		End Sub
	
	End Class
